"""m1_tenancy_user

Revision ID: 9ae719d05d64
Revises:
Create Date: 2026-10-05 19:04:04.597396

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ae719d05d64'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_tenant',
    sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='租户编码'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态: 0=正常,1=停用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_platform_tenant_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_platform_tenant_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_platform_tenant_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_tenant')),
    sa.UniqueConstraint('code'),
    comment='平台租户定义表'
    )
    with op.batch_alter_table('platform_tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_tenant_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_tenant_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_tenant_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_tenant_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_tenant_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_tenant_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_tenant_uuid'), ['uuid'], unique=True)

    # 先补默认租户行（id=1），否则下方 sys_user.tenant_id 的 server_default='1'
    # 回填的存量行会被 FK 拒绝（无对应 platform_tenant.id）。仅对「非空库升级」路径生效；
    # 全新库走 create_all + 种子 JSON，不经过本迁移。
    op.execute(
        "INSERT INTO platform_tenant "
        "(id, name, code, description, status, uuid, is_deleted, created_time, updated_time) "
        "VALUES (1, '默认租户', 'default', '平台初始化默认租户（存量数据回填目标）', 0, "
        "'00000000-0000-0000-0000-000000000001', false, now(), now())"
    )
    # 手工插入 id=1 后对齐序列，避免后续自增撞主键
    op.execute(
        "SELECT setval(pg_get_serial_sequence('platform_tenant', 'id'), "
        "(SELECT MAX(id) FROM platform_tenant))"
    )

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_sys_user_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sys_user_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sys_user_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sys_user_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('platform_tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_tenant_uuid'))
        batch_op.drop_index(batch_op.f('ix_platform_tenant_updated_id'))
        batch_op.drop_index(batch_op.f('ix_platform_tenant_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_platform_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_platform_tenant_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_platform_tenant_created_time'))
        batch_op.drop_index(batch_op.f('ix_platform_tenant_created_id'))

    op.drop_table('platform_tenant')
    # ### end Alembic commands ###
