"""m1_per_tenant_unique

Revision ID: 455436702bd8
Revises: 8fde066ce885
Create Date: 2026-10-06 08:58:39.271607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455436702bd8'
down_revision: Union[str, None] = '8fde066ce885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_dept', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sys_dept_code_key'), type_='unique')
        batch_op.create_unique_constraint('uq_sys_dept_tenant_code', ['tenant_id', 'code'])

    with op.batch_alter_table('sys_dict_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sys_dict_data_tenant_type_value', ['tenant_id', 'dict_type_id', 'dict_value'])

    with op.batch_alter_table('sys_dict_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_dict_type_dict_type'))
        batch_op.create_index(batch_op.f('ix_sys_dict_type_dict_type'), ['dict_type'], unique=False)
        batch_op.create_unique_constraint('uq_sys_dict_type_tenant_type', ['tenant_id', 'dict_type'])

    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sys_role_code_key'), type_='unique')
        batch_op.create_unique_constraint('uq_sys_role_tenant_code', ['tenant_id', 'code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sys_role_tenant_code', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('sys_role_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('sys_dict_type', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sys_dict_type_tenant_type', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sys_dict_type_dict_type'))
        batch_op.create_index(batch_op.f('ix_sys_dict_type_dict_type'), ['dict_type'], unique=True)

    with op.batch_alter_table('sys_dict_data', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sys_dict_data_tenant_type_value', type_='unique')

    with op.batch_alter_table('sys_dept', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sys_dept_tenant_code', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('sys_dept_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
