"""m1_tenancy_sysmodels

Revision ID: 999f3c209735
Revises: 9ae719d05d64
Create Date: 2026-10-05 20:56:35.554472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999f3c209735'
down_revision: Union[str, None] = '9ae719d05d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_dept', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_sys_dept_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sys_dept_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('sys_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_sys_position_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sys_position_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_sys_role_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sys_role_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sys_role_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sys_role_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('sys_position', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sys_position_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sys_position_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('sys_dept', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sys_dept_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sys_dept_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
