"""m1_user_tenant_m2m

Revision ID: 8fde066ce885
Revises: 9adf84b272b4
Create Date: 2026-10-05 21:47:51.862802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fde066ce885'
down_revision: Union[str, None] = '9adf84b272b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_user_tenant',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认租户'),
    sa.ForeignKeyConstraint(['tenant_id'], ['platform_tenant.id'], name=op.f('fk_platform_user_tenant_tenant_id_platform_tenant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_platform_user_tenant_user_id_sys_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id', name=op.f('pk_platform_user_tenant')),
    comment='用户租户关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_user_tenant')
    # ### end Alembic commands ###
