"""m1_tenancy_plugin

Revision ID: 9adf84b272b4
Revises: a99a025be045
Create Date: 2026-10-05 21:32:42.959659

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9adf84b272b4'
down_revision: str | None = 'a99a025be045'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gen_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_gen_table_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_gen_table_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('gen_table_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_gen_table_column_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_gen_table_column_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('task_corn_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_task_corn_job_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_corn_job_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('task_cornjob_node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_task_cornjob_node_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_cornjob_node_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('task_storage_workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_task_storage_workflow_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_storage_workflow_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('task_storage_workflow_edge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_task_storage_workflow_edge_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_storage_workflow_edge_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    with op.batch_alter_table('task_storage_workflow_node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_task_storage_workflow_node_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_storage_workflow_node_tenant_id_platform_tenant'), 'platform_tenant', ['tenant_id'], ['id'], ondelete='RESTRICT', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_storage_workflow_node', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_storage_workflow_node_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_storage_workflow_node_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('task_storage_workflow_edge', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_storage_workflow_edge_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_storage_workflow_edge_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('task_storage_workflow', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_storage_workflow_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_storage_workflow_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('task_cornjob_node', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_cornjob_node_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_cornjob_node_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('task_corn_job', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_corn_job_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_corn_job_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('gen_table_column', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gen_table_column_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_gen_table_column_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('gen_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gen_table_tenant_id_platform_tenant'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_gen_table_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
